### ISSUE TITLE
Question about installing the Pointnet++

### ISSUE THREAD

**Issue by wangmiaowei** [clinplayer/Point2Skeleton#4]
When I run the command:python setup.py build_ext --inplace
Something occures:
=0 -std=c++14
FAILED: /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/bindings.o
c++ -MMD -MF /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/bindings.o.d -pthread -B /mnt/f/Ubuntu_win/Anaconda/envs/dl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/TH -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/include/python3.6m -c -c /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/bindings.cpp -o /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/bindings.o -O2 -I./_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/bindings.cpp:1:10: fatal error: ball_query.h: No such file or directory
 #include "ball_query.h"
          ^~~~~~~~~~~~~~
compilation terminated.
[4/5] c++ -MMD -MF /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/group_points.o.d -pthread -B /mnt/f/Ubuntu_win/Anaconda/envs/dl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/TH -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/include/python3.6m -c -c /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/group_points.cpp -o /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/group_points.o -O2 -I./_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/group_points.o
c++ -MMD -MF /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/group_points.o.d -pthread -B /mnt/f/Ubuntu_win/Anaconda/envs/dl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/TH -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/include/python3.6m -c -c /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/group_points.cpp -o /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/group_points.o -O2 -I./_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/group_points.cpp:1:10: fatal error: group_points.h: No such file or directory
 #include "group_points.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
[5/5] c++ -MMD -MF /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/sampling.o.d -pthread -B /mnt/f/Ubuntu_win/Anaconda/envs/dl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/TH -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/include/python3.6m -c -c /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/sampling.cpp -o /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/sampling.o -O2 -I./_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/sampling.o
c++ -MMD -MF /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/sampling.o.d -pthread -B /mnt/f/Ubuntu_win/Anaconda/envs/dl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/TH -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/mnt/f/Ubuntu_win/Anaconda/envs/dl/include/python3.6m -c -c /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/sampling.cpp -o /mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/build/temp.linux-x86_64-3.6/_ext-src/src/sampling.o -O2 -I./_ext-src/include -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/mnt/f/Ubuntu_win/Project/Point2Skeleton/code/pointnet2/_ext-src/src/sampling.cpp:1:10: fatal error: sampling.h: No such file or directory
 #include "sampling.h"
          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions    build_ext.build_extensions(self)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/mnt/f/Ubuntu_win/Anaconda/envs/dl/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
It seems that the code do not read the .h file. How to sovle this problem?

**Comment by clinplayer** [comment]
Hi, this is a problem with PointNet installation. Could you please check if the instructions on https://github.com/erikwijmans/Pointnet2_PyTorch can help?

**Comment by xljh0520** [comment]
Hi，I met the same problem with you.  Could you tell me how to fix it?

**Comment by kninad** [comment]
I was able to resolve this error by using cuda 10.1 and pytorch 1.1.0 (https://pytorch.org/get-started/previous-versions/#v110)
