### ISSUE TITLE
When I run the program on Win10, I met  'forkserver' error

### ISSUE THREAD

**Issue by GuanTianQing** [clinplayer/Point2Skeleton#7]
Traceback (most recent call last):
  File "run_skeleton.py", line 6, in <module>
    from SkelPointNet import SkelPointNet
  File "E:\project\DongLuanProfessor\3D point Cloud\code\point2skeleton\Point2Skeleton-master\code\SkelPointNet.py", line 4, in <module>
    from pointnet2.utils.pointnet2_modules import PointnetSAModuleMSG
  File "E:\project\DongLuanProfessor\3D point Cloud\code\point2skeleton\Point2Skeleton-master\code\pointnet2\__init__.py", line 11, in <module>
    from pointnet2 import utils
  File "E:\project\DongLuanProfessor\3D point Cloud\code\point2skeleton\Point2Skeleton-master\code\pointnet2\utils\__init__.py", line 8, in <module>
    from . import pointnet2_utils
  File "E:\project\DongLuanProfessor\3D point Cloud\code\point2skeleton\Point2Skeleton-master\code\pointnet2\utils\pointnet2_utils.py", line 11, in <module>
    from . import etw_pytorch_utils as pt_utils
  File "E:\project\DongLuanProfessor\3D point Cloud\code\point2skeleton\Point2Skeleton-master\code\pointnet2\utils\etw_pytorch_utils\__init__.py", line 13, in <module>
    from .persistent_dataloader import DataLoader
  File "E:\project\DongLuanProfessor\3D point Cloud\code\point2skeleton\Point2Skeleton-master\code\pointnet2\utils\etw_pytorch_utils\persistent_dataloader.py", line 27, in <module>
    _mp_ctx = multiprocessing.get_context("forkserver")
  File "E:\software\Anaconda\envs\pytorch18\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "E:\software\Anaconda\envs\pytorch18\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method)
ValueError: cannot find context for 'forkserver'

**Comment by clinplayer** [comment]
Maybe this could help you

https://stackoverflow.com/questions/46021456/configure-multiprocessing-in-python-to-use-forkserver

**Comment by GuanTianQing** [comment]
@clinplayer Thank  you for your reply. solved it by  chaning  ` _mp_ctx = multiprocessing.get_context("forkserver")`  to
 `   _mp_ctx = multiprocessing.get_context("spawn")`
