### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by akamob** [clinplayer/Point2Skeleton#8]
When I run the command:**python setup.py build_ext --inplace**
I face some problems:
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/dodo/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/dodo/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/dodo/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/dodo/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 456, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/home/dodo/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/dodo/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

May i have your suggestions to fix this problem?
Any help is much appreciated:)

**Comment by clinplayer** [comment]
Hey, I cannot reproduce this problem. This is a problem for the pointnet++ installation, so could you please check if the issues or the guidelines in https://github.com/erikwijmans/Pointnet2_PyTorch can help?

We use exactly the same implementation and installation in **pointnet2_ops_lib** of the repository above.
